//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarenHarte_S00182304
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneDetails
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Price { get; set; }
        public string OperatingSystem { get; set; }
        public string OS_Image { get; set; }
        public string Phone_Image { get; set; }
    }
}
